# Generated by Django 2.1.2 on 2018-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='winning_per',
            field=models.IntegerField(default=0, verbose_name='勝率'),
        ),
    ]
