# Generated by Django 2.1.2 on 2018-10-19 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0, verbose_name='対戦回数')),
                ('wins', models.IntegerField(default=0, verbose_name='勝った数')),
                ('loses', models.IntegerField(default=0, verbose_name='負けた数')),
                ('hi_score', models.IntegerField(default=0, verbose_name='ハイスコア')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
