# Generated by Django 2.1.2 on 2018-10-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='スコア'),
            preserve_default=False,
        ),
    ]
