# Generated by Django 2.1.2 on 2018-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181023_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='name',
            field=models.CharField(max_length=200, verbose_name='プレイヤー名'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='stone',
            field=models.CharField(max_length=10, verbose_name='結果'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='win_or_lose',
            field=models.CharField(max_length=5, verbose_name='勝敗'),
        ),
    ]
